include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_import: ignore 
    unnecessary_brace_in_string_interps: ignore 
    unnecessary_string_interpolations: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore
