name: ecommerce_my_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  cloud_firestore: 6.1.0 
  image_picker: ^1.1.2 
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  provider: ^6.1.1  
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  google_sign_in: ^6.3.0
  google_identity_services_web: ^0.3.3+1
  flutter_masked_text2: ^0.9.1
  mask_text_input_formatter: ^2.4.0
  http: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/svgs/
